language: objective-c
 
branches:
 only:
 - master
 
osx_image: xcode7.2
xcode_sdk: macosx10.11 
 
script:
- xcodebuild clean build -project Run-Forrest-Run.xcodeproj -scheme Run-Forrest-Run
- xcodebuild test -project Run-Forrest-Run.xcodeproj -scheme Run-Forrest-Run-Tests
